export const SCENARIO_PRESETS = [
  {
    id: 'electronics-launch',
    label: 'Điện tử xuất khẩu',
    description:
      'Preset cho lô hàng điện tử ưu tiên tỷ lệ lấp đầy và phân bổ tải đều trong 40 HC.',
    containerType: '40hc',
    floorLoadLimit: 0,
    commercialSettings: {
      projectName: 'Electronics Launch Wave',
      customerName: 'Pacific Retail Group',
      routeName: 'Ho Chi Minh City -> Los Angeles',
      serviceLevel: 'priority',
      declaredValue: 420000,
      freightCost: 4100,
      targetUtilization: 88,
      targetMaxImbalance: 9,
    },
    items: [
      {
        id: 1101,
        label: 'TV 43 inch',
        w: 68,
        h: 14,
        d: 108,
        weight: 15,
        qty: 36,
        allowRotate: true,
        noStack: true,
        noTilt: true,
        priorityGroup: 3,
        stackLimit: 1,
        maxLoadAbove: 0,
        deliveryZone: 'door',
      },
      {
        id: 1102,
        label: 'Soundbar',
        w: 18,
        h: 16,
        d: 105,
        weight: 8,
        qty: 28,
        allowRotate: true,
        noStack: false,
        noTilt: true,
        priorityGroup: 2,
        stackLimit: 2,
        maxLoadAbove: 24,
        deliveryZone: 'middle',
      },
      {
        id: 1103,
        label: 'Loa mini',
        w: 32,
        h: 28,
        d: 42,
        weight: 6,
        qty: 60,
        allowRotate: true,
        noStack: false,
        noTilt: false,
        priorityGroup: 1,
        stackLimit: 4,
        maxLoadAbove: 50,
        deliveryZone: 'head',
      },
      {
        id: 1104,
        label: 'Phụ kiện',
        w: 24,
        h: 22,
        d: 36,
        weight: 4,
        qty: 90,
        allowRotate: true,
        noStack: false,
        noTilt: false,
        priorityGroup: 1,
        stackLimit: 5,
        maxLoadAbove: 80,
        deliveryZone: 'head',
      },
    ],
  },
  {
    id: 'fashion-crossborder',
    label: 'Thời trang cross-border',
    description:
      'Preset cho lô hàng e-commerce nhiều SKU, phù hợp demo xếp hỗn hợp trong 20 Dry.',
    containerType: '20dc',
    floorLoadLimit: 0,
    commercialSettings: {
      projectName: 'Cross-border Fashion Drop',
      customerName: 'North America Marketplace',
      routeName: 'Ho Chi Minh City -> Dallas',
      serviceLevel: 'standard',
      declaredValue: 168000,
      freightCost: 2650,
      targetUtilization: 84,
      targetMaxImbalance: 11,
    },
    items: [
      {
        id: 1201,
        label: 'Carton áo khoác',
        w: 48,
        h: 34,
        d: 58,
        weight: 12,
        qty: 42,
        allowRotate: true,
        noStack: false,
        noTilt: false,
        priorityGroup: 2,
        stackLimit: 4,
        maxLoadAbove: 45,
        deliveryZone: 'door',
      },
      {
        id: 1202,
        label: 'Carton sneaker',
        w: 44,
        h: 33,
        d: 62,
        weight: 14,
        qty: 30,
        allowRotate: true,
        noStack: false,
        noTilt: false,
        priorityGroup: 2,
        stackLimit: 3,
        maxLoadAbove: 38,
        deliveryZone: 'middle',
      },
      {
        id: 1203,
        label: 'Carton túi xách',
        w: 40,
        h: 30,
        d: 52,
        weight: 10,
        qty: 26,
        allowRotate: true,
        noStack: false,
        noTilt: false,
        priorityGroup: 1,
        stackLimit: 4,
        maxLoadAbove: 32,
        deliveryZone: 'head',
      },
      {
        id: 1204,
        label: 'Hàng hoàn dễ móp',
        w: 36,
        h: 26,
        d: 44,
        weight: 7,
        qty: 18,
        allowRotate: true,
        noStack: true,
        noTilt: false,
        priorityGroup: 3,
        stackLimit: 1,
        maxLoadAbove: 0,
        deliveryZone: 'door',
      },
    ],
  },
  {
    id: 'heavy-spare-parts',
    label: 'Phụ tùng nặng',
    description:
      'Preset cho hàng phụ tùng cơ khí có giới hạn tải sàn, dùng để demo cảnh báo và heuristic cân bằng tải.',
    containerType: '40dc',
    floorLoadLimit: 1650,
    commercialSettings: {
      projectName: 'Heavy Parts Refill',
      customerName: 'Industrial Service Network',
      routeName: 'Hai Phong -> Rotterdam',
      serviceLevel: 'priority',
      declaredValue: 560000,
      freightCost: 5200,
      targetUtilization: 80,
      targetMaxImbalance: 8,
    },
    items: [
      {
        id: 1301,
        label: 'Motor điện',
        w: 72,
        h: 62,
        d: 78,
        weight: 145,
        qty: 12,
        allowRotate: false,
        noStack: true,
        noTilt: true,
        priorityGroup: 3,
        stackLimit: 1,
        maxLoadAbove: 0,
        deliveryZone: 'head',
      },
      {
        id: 1302,
        label: 'Khung thép',
        w: 88,
        h: 48,
        d: 126,
        weight: 170,
        qty: 10,
        allowRotate: true,
        noStack: false,
        noTilt: true,
        priorityGroup: 2,
        stackLimit: 2,
        maxLoadAbove: 180,
        deliveryZone: 'middle',
      },
      {
        id: 1303,
        label: 'Bộ bánh răng',
        w: 56,
        h: 42,
        d: 64,
        weight: 62,
        qty: 24,
        allowRotate: true,
        noStack: false,
        noTilt: false,
        priorityGroup: 1,
        stackLimit: 3,
        maxLoadAbove: 95,
        deliveryZone: 'door',
      },
      {
        id: 1304,
        label: 'Thùng dụng cụ',
        w: 38,
        h: 32,
        d: 52,
        weight: 26,
        qty: 40,
        allowRotate: true,
        noStack: false,
        noTilt: false,
        priorityGroup: 1,
        stackLimit: 4,
        maxLoadAbove: 60,
        deliveryZone: 'door',
      },
    ],
  },
];
